[package]
name = "markdown-composer"
version = "0.2.3"
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."

[dependencies]
aurelius = { path = "../aurelius" }
clap = "2"
log = "0.4"
log-panics = { version = "2", features = ["with-backtrace"] }
log4rs = "0.8"
serde = "1"
serde_derive = "1"
shlex = "0.1"

serde_json = { version = "1", optional = true }
rmp-serde = { version = "0.13", optional = true }

[features]
default = ["msgpack"]
msgpack = ["rmp-serde"]
json-rpc = ["serde_json"]
